/* GENERATED by tools/mkcutscenes.py -- do not edit.
 * Where each level's cutscene screen lives in banked RAM.
 */
#ifndef _CUTSCENES_H_
#define _CUTSCENES_H_

#include <stdint.h>

#define CUTSCENE_COUNT 10

static const uint8_t cutscene_bank[CUTSCENE_COUNT] = {
    1, 1, 1, 1, 1, 1, 3, 3, 3, 3
};

static const uint16_t cutscene_off[CUTSCENE_COUNT] = {
    0x0100, 0x0AD7, 0x14AE, 0x1E85, 0x285C, 0x3233, 0x0000, 0x09D7, 0x13AE, 0x1D85
};

#endif /* _CUTSCENES_H_ */
