/* GENERATED by tools/mklevels.py from levels.json -- do not edit. */

#ifndef _LEVELS_H_
#define _LEVELS_H_

#include <stdint.h>

#define LEVEL_BOOK_COUNT 10

/* Turns allowed, per level.  ST_PLAY shows what is LEFT of this
   and the level score is whatever was not spent. */
static const uint8_t level_turns[LEVEL_BOOK_COUNT] = {
    20,20,20,20,20,20,20,20,20,20
};

/* Dateline then briefing, NUL-terminated, per level.
   1367 bytes raw, ZX0 to 729.  Unpacked into MEM_VBUF by ST_BRIEF:
   the compose buffer is idle there and render_play() rebuilds it. */
#define LEVEL_BRIEF_RAW 1367

static const uint16_t level_brief_off[LEVEL_BOOK_COUNT] = {
    0,214,371,528,613,679,802,1046,1150,1288
};

extern const uint8_t level_brief_zx0[729];

/* The mission titles, by level.  Pointers into the resident
   string pool: the header is drawn while the board is composed,
   so these cannot live in the briefing block. */
extern const char *const level_mission[LEVEL_BOOK_COUNT];

#endif /* _LEVELS_H_ */
