/* GENERATED by tools/mktext.py from ../text/strings.txt -- do not edit. */

#ifndef _STRINGS_H_
#define _STRINGS_H_

#include <stdint.h>

#include "memmap.h"

/* The pool is ZX0 in the program and unpacked to a FIXED address
   at boot, so every string's address is known here.  TXT_* is a
   constant, costing one `ld hl,nn` at the call site -- the same
   as the plain array it replaced. */
#define TEXT_COUNT      54
#define TEXT_POOL_SIZE  716

void text_init(void);

#define TXT_ENEMY_TURN                     ((const char *)(MEM_TEXTPOOL + 0))   /* '      ENEMY TURN' */
#define TXT_ENEMY                          ((const char *)(MEM_TEXTPOOL + 17))   /* 'ENEMY  :' */
#define TXT_CURSOR                         ((const char *)(MEM_TEXTPOOL + 26))   /* 'CURSOR :' */
#define TXT_BLANK                          ((const char *)(MEM_TEXTPOOL + 35))   /* '' */
#define TXT_QAOP_PICK_SPACE_FIRE_ENTER_B   ((const char *)(MEM_TEXTPOOL + 36))   /* 'QAOP PICK  SPACE FIRE ENTER BACK' */
#define TXT_UNIT                           ((const char *)(MEM_TEXTPOOL + 69))   /* 'UNIT   :' */
#define TXT_BLANK_2                        ((const char *)(MEM_TEXTPOOL + 78))   /* '-                      ' */
#define TXT_TURN                           ((const char *)(MEM_TEXTPOOL + 102))   /* 'TURN   :' */
#define TXT_TERRAIN                        ((const char *)(MEM_TEXTPOOL + 111))   /* 'TERRAIN:' */
#define TXT_COVER                          ((const char *)(MEM_TEXTPOOL + 120))   /* 'COVER' */
#define TXT_THE_FIELD                      ((const char *)(MEM_TEXTPOOL + 126))   /* 'THE FIELD' */
#define TXT_CAMPAIGN_MAP                   ((const char *)(MEM_TEXTPOOL + 136))   /* 'CAMPAIGN MAP' */
#define TXT_QAOP_LOOK_AROUND_ENTER_BACK    ((const char *)(MEM_TEXTPOOL + 149))   /* 'QAOP LOOK AROUND  ENTER BACK' */
#define TXT_CAMPAIGN_COMPLETE              ((const char *)(MEM_TEXTPOOL + 178))   /* 'CAMPAIGN COMPLETE' */
#define TXT_EVERY_LEVEL_TAKEN              ((const char *)(MEM_TEXTPOOL + 196))   /* 'EVERY LEVEL TAKEN' */
#define TXT_LEVELS_WON                     ((const char *)(MEM_TEXTPOOL + 214))   /* 'LEVELS WON     :' */
#define TXT_FINAL_SCORE                    ((const char *)(MEM_TEXTPOOL + 231))   /* 'FINAL SCORE    :' */
#define TXT_SPACE_FIRE_1                   ((const char *)(MEM_TEXTPOOL + 248))   /* 'SPACE / FIRE 1' */
#define TXT_ZX_STRATEGY                    ((const char *)(MEM_TEXTPOOL + 263))   /* 'ZX STRATEGY' */
#define TXT_MACHINE                        ((const char *)(MEM_TEXTPOOL + 275))   /* 'MACHINE :' */
#define TXT_T_128K                         ((const char *)(MEM_TEXTPOOL + 285))   /* '128K' */
#define TXT_T_48K                          ((const char *)(MEM_TEXTPOOL + 290))   /* '48K' */
#define TXT_KEMPSTON                       ((const char *)(MEM_TEXTPOOL + 294))   /* 'KEMPSTON:' */
#define TXT_YES                            ((const char *)(MEM_TEXTPOOL + 304))   /* 'YES' */
#define TXT_NO                             ((const char *)(MEM_TEXTPOOL + 308))   /* 'NO' */
#define TXT_VSYNC                          ((const char *)(MEM_TEXTPOOL + 311))   /* 'VSYNC   :' */
#define TXT_FLOATING_BUS_0X                ((const char *)(MEM_TEXTPOOL + 321))   /* 'FLOATING BUS 0X' */
#define TXT_T_40FF                         ((const char *)(MEM_TEXTPOOL + 337))   /* '40FF' */
#define TXT_T_0FFD                         ((const char *)(MEM_TEXTPOOL + 342))   /* '0FFD' */
#define TXT_HALT_FALLBACK                  ((const char *)(MEM_TEXTPOOL + 347))   /* 'HALT FALLBACK  ' */
#define TXT_SCREEN                         ((const char *)(MEM_TEXTPOOL + 363))   /* 'SCREEN  :' */
#define TXT_DOUBLE                         ((const char *)(MEM_TEXTPOOL + 373))   /* 'DOUBLE' */
#define TXT_SINGLE                         ((const char *)(MEM_TEXTPOOL + 380))   /* 'SINGLE' */
#define TXT_SPACE_FIRE_1_START             ((const char *)(MEM_TEXTPOOL + 387))   /* 'SPACE / FIRE 1   START' */
#define TXT_QAOP_KEMPSTON_MOVE             ((const char *)(MEM_TEXTPOOL + 410))   /* 'QAOP / KEMPSTON  MOVE' */
#define TXT_SPACE_FIRE_1_DO                ((const char *)(MEM_TEXTPOOL + 432))   /* 'SPACE / FIRE 1   DO' */
#define TXT_ENTER_FIRE_2_BACK              ((const char *)(MEM_TEXTPOOL + 452))   /* 'ENTER / FIRE 2   BACK' */
#define TXT_VICTORY                        ((const char *)(MEM_TEXTPOOL + 474))   /* 'VICTORY' */
#define TXT_DEFEAT                         ((const char *)(MEM_TEXTPOOL + 482))   /* 'DEFEAT' */
#define TXT_LEVEL_TAKEN                    ((const char *)(MEM_TEXTPOOL + 489))   /* 'LEVEL TAKEN    :' */
#define TXT_LEVEL_LOST                     ((const char *)(MEM_TEXTPOOL + 506))   /* 'LEVEL LOST     :' */
#define TXT_TURNS_TAKEN                    ((const char *)(MEM_TEXTPOOL + 523))   /* 'TURNS TAKEN    :' */
#define TXT_LEVEL_SCORE                    ((const char *)(MEM_TEXTPOOL + 540))   /* 'LEVEL SCORE    :' */
#define TXT_TOTAL_SCORE                    ((const char *)(MEM_TEXTPOOL + 557))   /* 'TOTAL SCORE    :' */
#define TXT_SPACE_FOR_THE_NEXT_LEVEL       ((const char *)(MEM_TEXTPOOL + 574))   /* 'SPACE FOR THE NEXT LEVEL' */
#define TXT_SPACE_TO_RETURN_TO_THE_TITLE   ((const char *)(MEM_TEXTPOOL + 599))   /* 'SPACE TO RETURN TO THE TITLE' */
#define TXT_UNIT_INFANTRY                  ((const char *)(MEM_TEXTPOOL + 628))   /* 'Red Shadow' */
#define TXT_UNIT_TANK                      ((const char *)(MEM_TEXTPOOL + 639))   /* 'Red Hyena ' */
#define TXT_UNIT_CANNON                    ((const char *)(MEM_TEXTPOOL + 650))   /* 'Las Cannon' */
#define TXT_UNIT_BASE                      ((const char *)(MEM_TEXTPOOL + 661))   /* 'Red Base  ' */
#define TXT_UNIT_E_INFANTRY                ((const char *)(MEM_TEXTPOOL + 672))   /* 'E-INFANTRY' */
#define TXT_UNIT_E_TANK                    ((const char *)(MEM_TEXTPOOL + 683))   /* 'E-TANK    ' */
#define TXT_UNIT_E_CANNON                  ((const char *)(MEM_TEXTPOOL + 694))   /* 'E-CANNON  ' */
#define TXT_UNIT_E_BASE                    ((const char *)(MEM_TEXTPOOL + 705))   /* 'E-BASE    ' */

#endif /* _STRINGS_H_ */
