#!/usr/bin/env python3
"""Pack the per-level cutscene screens into RAM banks.

Compresses each assets/cutscenes/level_N.scr with ZX0, lays them out
across the banks that are actually free on a 128K, and emits:

  include/cutscenes.h   the bank and offset for each level, for render.c
  cutscenes.args        the --bank arguments for tools/mktap.py

The layout is COMPUTED, never written down by hand.  Art changes size
whenever it is redrawn, and this session has twice lost hours to an
address that was typed rather than generated -- see
.claude/skills/zx-loader § Drive mktap from the BUILD.

Which banks, and why they are the only ones:

  0  mapped at 0xC000 at boot; usable, but left alone as a safety margin
  1  hw_detect() scratches OFFSET 0 proving the machine is a 128K
  2  PERMANENTLY at 0x8000 -- this is the program
  5  PERMANENTLY at 0x4000 -- screen and contended data
  7  the shadow screen, and every buffer from 0xDB00 up
"""

import os
import subprocess
import sys

BANKS = [1, 3, 4, 6]        # 2, 5 and 7 are spoken for; 0 is margin
BANK_SIZE = 0x4000
FIRST_FREE = {1: 0x0100}    # hw_detect owns bank 1 offset 0
STAGE_MAX = 6912            # a blob is copied through the display file


def main():
    zx0 = sys.argv[1]
    srcs = sorted(sys.argv[2:],
                  key=lambda p: int(''.join(c for c in os.path.basename(p)
                                            if c.isdigit())))
    os.makedirs('build/cutscenes', exist_ok=True)

    blobs = []
    for src in srcs:
        out = 'build/cutscenes/' + os.path.basename(src).replace('.scr', '.zx0')
        if os.path.exists(out):
            os.remove(out)
        subprocess.run([zx0, '-f', src, out], check=True, capture_output=True)
        data = open(out, 'rb').read()
        if len(data) > STAGE_MAX:
            sys.exit(f'mkcutscenes: {src} is {len(data)} bytes compressed, '
                     f'over the {STAGE_MAX}-byte staging limit -- it cannot '
                     f'be copied through the display file in one pass')
        blobs.append((out, data))

    bi = 0
    off = FIRST_FREE.get(BANKS[0], 0)
    placed = []
    for out, data in blobs:
        if off + len(data) > BANK_SIZE:
            bi += 1
            if bi >= len(BANKS):
                sys.exit(f'mkcutscenes: out of banks at {out} -- '
                         f'{len(BANKS)} x 16K holds only so much')
            off = FIRST_FREE.get(BANKS[bi], 0)
        placed.append((BANKS[bi], off, out, len(data)))
        off += len(data)

    with open('include/cutscenes.h', 'w') as f:
        f.write('/* GENERATED by tools/mkcutscenes.py -- do not edit.\n'
                ' * Where each level\'s cutscene screen lives in banked RAM.\n'
                ' */\n#ifndef _CUTSCENES_H_\n#define _CUTSCENES_H_\n\n'
                '#include <stdint.h>\n\n')
        f.write(f'#define CUTSCENE_COUNT {len(placed)}\n\n')
        f.write('static const uint8_t cutscene_bank[CUTSCENE_COUNT] = {\n    ')
        f.write(', '.join(str(b) for b, _, _, _ in placed))
        f.write('\n};\n\nstatic const uint16_t cutscene_off[CUTSCENE_COUNT] = {\n    ')
        f.write(', '.join(f'0x{o:04X}' for _, o, _, _ in placed))
        f.write('\n};\n\n#endif /* _CUTSCENES_H_ */\n')

    with open('cutscenes.args', 'w') as f:
        f.write(' '.join(f'--bank {b} 0x{o:04X} {p}'
                         for b, o, p, _ in placed))

    used = {}
    for b, o, _, n in placed:
        used[b] = used.get(b, 0) + n
    print('mkcutscenes: %d screens, %d bytes' %
          (len(placed), sum(n for _, _, _, n in placed)))
    for b in sorted(used):
        print('       bank %d: %5d bytes, %5d free' %
              (b, used[b], BANK_SIZE - used[b] - FIRST_FREE.get(b, 0)))


main()
