#!/usr/bin/env python3
"""mkfont.py — a .ch8 font binary -> src/font.c

A .ch8 is the ZX Spectrum's own font layout: 8 bytes per glyph, one bit
per pixel, MSB left, starting at character 32 (space).  That is exactly
how the ROM stores its font at 0x3D00, so a replacement is a pointer
change and nothing else.

THE ROM CANNOT BE OVERWRITTEN.  0x0000-0x3FFF is read-only on every
Spectrum, so "replace the font" means putting one in RAM and pointing the
printer at it.  print_at() reads `game_font` rather than 0x3D00; the
arithmetic is identical because the layout is identical.

NOT COMPRESSED, deliberately.  ZX0 takes the 768 bytes to 451, but the
decompressed copy still has to live somewhere print_at() can read it
every glyph, and there is not 768 bytes of RAM spare above MEM_END.
Compressing it would trade 317 bytes of the program region for 768 bytes
of a region that has less.  If that ever changes -- if a buffer up there
is retired -- this becomes worth revisiting, and the change is one call
to dzx0_decompress() at boot.

A SUBSET was measured too.  The game prints 50 distinct characters, but
they run from space to lowercase 'y' (the unit names are mixed case), so
a subset saves 48 bytes of the 768 and introduces a cliff the moment
somebody types a 'z'.  Not worth it.
"""

import argparse
import os
import sys

GLYPH = 8
FIRST = 32          # the ROM's font starts at space, and so does .ch8


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input", help="a .ch8 font: 8 bytes per glyph from ' '")
    ap.add_argument("-o", "--output", required=True, help="output .c")
    ap.add_argument("--name", default="game_font")
    args = ap.parse_args()

    data = open(args.input, "rb").read()
    if len(data) % GLYPH:
        sys.exit("mkfont: %d bytes is not a whole number of 8-row glyphs"
                 % len(data))
    n = len(data) // GLYPH
    if n < 64:
        sys.exit("mkfont: only %d glyphs; a usable font needs at least the "
                 "printable ASCII range" % n)

    # A font of all-zero or all-set glyphs is a file that loaded but is
    # not a font -- worth catching here rather than on a blank screen.
    ink = sum(bin(b).count("1") for b in data)
    if ink < len(data) or ink > len(data) * 7:
        sys.exit("mkfont: %d ink bits in %d bytes -- that does not look "
                 "like glyph data" % (ink, len(data)))

    out = ["/* GENERATED by tools/mkfont.py from %s -- do not edit. */"
           % os.path.basename(args.input),
           "",
           "#include <stdint.h>",
           "",
           "/* %d glyphs from character %d, 8 rows each: the ROM's own layout,"
           % (n, FIRST),
           "   so print_at() indexes it exactly as it indexed 0x3D00. */",
           "const uint8_t %s[%d] = {" % (args.name, len(data))]
    for i in range(0, len(data), GLYPH):
        ch = FIRST + i // GLYPH
        pretty = chr(ch) if 32 < ch < 127 else " "
        out.append("    %s   /* %3d %s */"
                   % (",".join("0x%02X" % b for b in data[i:i + GLYPH]) + ",",
                      ch, pretty))
    out += ["};", ""]
    open(args.output, "w").write("\n".join(out))
    print("mkfont: %d glyphs, %d bytes -> %s" % (n, len(data), args.output))


if __name__ == "__main__":
    sys.exit(main())
