; Generated by tools/mkassets.py -- do not edit.
; Addresses only, no bytes: these resolve the extern
; declarations in the generated headers to the standalone
; blob loaded at 0x6000, and cost nothing.

    MODULE  assets_low_syms

    PUBLIC  _tiles_view_zx0
    defc    _tiles_view_zx0 = 0x6000
    PUBLIC  _units_view_zx0
    defc    _units_view_zx0 = 0x617C
    PUBLIC  _tiles_map_zx0
    defc    _tiles_map_zx0 = 0x62AC
    PUBLIC  _units_map_zx0
    defc    _units_map_zx0 = 0x630E
