; Generated by tools/mkassets.py -- do not edit.
;
; Puts logic.c in the contended window below the program.  It is
; the right module for it: AI and pathfinding run once per turn,
; not once per frame, so the ULA stealing a cycle from every fetch
; costs nothing measurable -- the state walk is unchanged at ~19s.
; Moving ALL code down here instead cost about 50%.  The render
; path stays at 0x8000 for that reason.
;
; 0x6500 is the first free byte after the asset blobs.
    SECTION LOGIC
    org     0x6500
